mode: dev-k8s
password_salt: 456234
jwt_refresh_secret: hfhdj567ghj45hjkdfcvx456vbn
jwt_access_secret: df345sdfsdfas234dfasdfa567sdf
cookie_refresh_token_max_age: 604800
cookie_refresh_token_domain: kubernetes.docker.internal
port: 5003
rabbit_mq_url: amqps://rabbitmq-service:5672
rabbit_mq_user_queue: user
tls_server_name: auth-service-service
postgres_host: postgres-service
postgres_port: 5432
postgres_user: postgres
postgres_password: prisma
postgres_database: auth-service
