mode: dev-docker
password_salt: 456234
jwt_refresh_secret: hfhdj567ghj45hjkdfcvx456vbn
jwt_access_secret: df345sdfsdfas234dfasdfa567sdf
cookie_refresh_token_max_age: 604800
cookie_refresh_token_domain: localhost
port: 5003
health_port: 35003
rabbit_mq_url: amqps://host.docker.internal:5672
rabbit_mq_user_queue: user
tls_server_name: host.docker.internal
postgres_tls_server_name: host.docker.internal
rabbitmq_tls_server_name: host.docker.internal
postgres_host: host.docker.internal
postgres_port: 5433
postgres_user: prisma
postgres_password: prisma
postgres_database: auth-service
