name: deploy

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      # https://github.com/orgs/community/discussions/26302
      matrix:
        service:
          [
            auth-service,
            billing-service,
            subscription-service,
            map-service,
            chat-service,
            user-service,
            file-service,
          ]
        include:
          - service: auth-service
            repo_secret: AUTH_SERVICE_REPO_NAME
            root_path: ./auth-service
          - service: billing-service
            repo_secret: BILLING_SERVICE_REPO_NAME
            root_path: ./billing-service
          - service: subscription-service
            repo_secret: SUBSCRIPTION_SERVICE_REPO_NAME
            root_path: ./subscription-service
          - service: map-service
            repo_secret: MAP_SERVICE_REPO_NAME
            root_path: ./map-service
          - service: chat-service
            repo_secret: CHAT_SERVICE_REPO_NAME
            root_path: .
          - service: user-service
            repo_secret: USER_SERVICE_REPO_NAME
            root_path: .
          - service: file-service
            repo_secret: FILE_SERVICE_REPO_NAME
            root_path: ./file-service

    steps:
      - uses: actions/checkout@v4
      - name: Extract clean version
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build and push image
        uses: docker/build-push-action@v6
        env:
          APP_TAG: ${{ steps.get_version.outputs.VERSION }}
        with:
          context: ${{ matrix.root_path }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets[matrix.repo_secret] }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
