name: file-service-ci

on:
  push:
    paths:
      - 'file-service/**'

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/golang-service-ci
        with:
          service-path: ./file-service
          docker-build: 'true'
